language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"

env:
  matrix:
    - DJANGO=1.6
    - DJANGO=1.7
    - DJANGO=1.8
    - DJANGO=1.9

install:
  - TOX_ENV=py${TRAVIS_PYTHON_VERSION}-django${DJANGO}
  - pip install tox coveralls

script:
  - tox -e $TOX_ENV

after_success:
  - tox -e $TOX_ENV -- coveralls $COVERALLS_OPTION

matrix:
  fast_finish: true
  allow_failures:
    - python: "pypy3"
  include:
    - python: "3.4"
      env: ENV=lint
      script: tox -e lint
  exclude:
    - python: "3.5"
      env: DJANGO=1.6
    - python: "3.5"
      env: DJANGO=1.7
    - python: "pypy3"
      env: DJANGO=1.6
    - python: "3.3"
      env: DJANGO=1.9
